Algoritmo "carro"
Disciplina : [PA] 
Professora : Cintia Pinho 
Autor(a) : Gabriela Ripoli
Dados atuais : 28/09/2021 
Var
idade: inteiro
resp:caracter


Inicio
entrada 
escreval ("qual a sua idade:") 
leia(idade)

escreval ("Possui habilitação:") 
leia (resp)

decisão 

se ((idade>=18) e (resp="sim")) entao

   escreval ("Pode Passar!")

senao
 escreval ("Nao pode passar!") 
fimse


Fimalgoritmo